// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG1OAdfzSlTfz_5KmlrwMBewMMvIWN3V4',
    appId: '1:822399296694:android:b62e6e495a1f224253b217',
    messagingSenderId: '822399296694',
    projectId: 'piwot-b559b',
    storageBucket: 'piwot-b559b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaeYHnFKEiVUNLvK9ICgI8iboh9KOMCyg',
    appId: '1:822399296694:ios:223c4e900f52cb9153b217',
    messagingSenderId: '822399296694',
    projectId: 'piwot-b559b',
    storageBucket: 'piwot-b559b.appspot.com',
    iosBundleId: 'com.kdc.piwotapp',
  );

}
